### PR TITLE
build: Add Dockerfile, a run script, and instructions for usage

### PR DESCRIPTION
**Pull request by kylegalloway**
This adds the ability to build/run from a Docker container.

### CODE REVIEW

**Comment by codewithtyler** [comment]
Ok so I'm testing this on Windows at the moment. It does give me this warning after running docker build:

`SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.`

When I use the docker run command you provided I get this error:
```
unknown shorthand flag: 'g' in -g`
```

**Review by mjcarroll — APPROVED** [review]
Looks reasonable to me, thanks for the contribution.

Currently I'm deploying the production to Heroku, so we're not utilizing docker, but this would be useful if it's moved to another service.

**Comment by kylegalloway** [comment]
> Ok so I'm testing this on Windows at the moment. It does give me this warning after running docker build:
> 
> `SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.`
> 
> When I use the docker run command you provided I get this error:
> 
> ```
> unknown shorthand flag: 'g' in -g`
> ```

The warning is just telling you that all of your files in the build context (i.e. all of the files that Docker pulls into the container) will have 755 permissions.

The error is for the -u flag. It is a flag that allows you to set the user inside the Docker container. In my instructions I set the user to be whoever is running the container. This flag can be omitted, however, it will result in many files being wriitten/owned by "root". This makes it where any file management must be done as admin (which is possible, but bad practice).

Possible fixes for this on Windows: Give a set user id and group id (e.g. 1000:1000), omit the flag.

More information https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15

Official docs: https://docs.docker.com/engine/reference/run/#user

**Comment by mjcarroll** [comment]
> Possible fixes for this on Windows: Give a set user id and group id (e.g. 1000:1000), omit the flag.

Or install Linux :)

**Comment by codewithtyler** [comment]
@mjcarroll yeah not an option for me

**Pull request closed without merging**
